---
title: 'RMarkdown:  In Class Assignment'
author: "Benjamin Pham"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.


2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 

# Your Work Here
 
## Wise words
 
 ```
  Thoedore Roosevelt once said:
  
  > In any moment of decision, the best thing you can do is the right thing
  > the next best thing is the wrong thing
  > and the worst thing you can do is nothing
 ``` 
 
[link phrase](https://www.brainyquote.com/topics/the-right-thing-quotes#:~:text=In%20any%20moment%20of%20decision,you%20can%20do%20is%20nothing.&text=You%20can%20always%20count%20on,they%27ve%20tried%20everything%20else.) 


## My semester

| __Course Number__ |  _Course Title_  | Instrutor Name      |
|:------------------|:-----------------|:--------------------|
|     __2401__      | _Data Science_   | Katherine Shoemaker |
|     __2305__      | _Prob & Stats_   | Vien Nguyen         |
|     __2307__      | _Linear Algebra_ | Sergiy Koshkin      |

## I recommened

## LISA

```
Baila, what you want? Dance for you
I'll sway, sway all night with you
Baila, come on in close to you
Ah, ah, ah, ayy, yeah
'Til the sun comes up, I'll be here with you
No lie, no lie
Got me in the mood when it's just us two
I'll fly, I'll fly, yeah, ah
Sexy girl 
You know I don't play
Make you fall in love
One touch and you'll be saved
On fire 
Why won't you behave? 
My love gon' send you walking to a higher place, oh, oh
```
+ SG
+ Ice Cream
+ WHISTLE
